src/main/default/objects/Adoption__c/Adoption__c.object-meta.xml
<CustomObject>
    <label>Adoption</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Subscription Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Adoptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/Adoption__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Adoptions</relationshipLabel>
    <relationshipName>Adoptions</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Adoption__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/main/default/classes/AdoptionTriggerHandler.cls
/**
 * @description       : 
 * @author            : Sorin Ciubotaru BearingPoint GmbH
 * @group             : 
 * @last modified on  : 02-21-2023
 * @last modified by  : Sorin Ciubotaru, BearingPoint GmbH
**/
public with sharing class AdoptionTriggerHandler {
    public static void checkAdoptionDuplicate(List<Adoption__c> newAdoptions) {
        Set<Id> relevantAccountIds = new Set<Id>();
        Set<Id> relevantAnimalIds = new Set<Id>();
        Set<Id> adoptionsFromTriggerIds = new Set<Id>();
        Map<Id, List<Adoption__c>> newAdoptionsByAccountId = new Map<Id,List<Adoption__c>>();
        for(Adoption__c adop : newAdoptions) {
            System.debug(adop.Account__c);
            System.debug(adop.Animal__c);
            adoptionsFromTriggerIds.add(adop.Id);

            if (!newAdoptionsByAccountId.containsKey(adop.Account__c)) {
                newAdoptionsByAccountId.put(adop.Account__c, new List<Adoption__c>());
            }

            newAdoptionsByAccountId.get(adop.Account__c).add(adop);
        }

        List<Adoption__c> existingAdoptions = [SELECT Account__c, Animal__c FROM Adoption__c 
        WHERE (Status__c = 'Active' 
        AND (Account__c IN :relevantAccountIds 
        OR Account__c IN :relevantAnimalIds) 
        AND ID NOT IN :adoptionsFromTriggerIds)];

        for(Adoption__C  existingAdoption : existingAdoptions)  {
            List<Adoption__c> newAdoptionsWithSameName = newAdoptionsByAccountId.get(existingAdoption.Account__c);
            if(newAdoptionsWithSameName != null) {
                for (Adoption__c newAdoptionSameName : newAdoptionsWithSameName)  {
                    if (newAdoptionSameName.Animal__c.equals(existingAdoption.Animal__c)){
                        newAdoptionSameName.addError('This record ia a duplicate!');
                    }
                    
                }
            }
        }
    }
}